# Generated by Django 5.1.3 on 2024-11-24 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер казармы')),
                ('capacity', models.IntegerField(verbose_name='Вместительность')),
                ('designation', models.CharField(choices=[('O', 'Офицеры'), ('S', 'Рядовые')], max_length=1, verbose_name='Назначение')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оружия')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='Табельный номер')),
            ],
        ),
        migrations.CreateModel(
            name='Soldier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('service_start_date', models.DateField(verbose_name='Дата начала службы')),
                ('service_end_date', models.DateField(verbose_name='Дата окончания службы')),
                ('barrack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.barrack', verbose_name='Казарма')),
                ('weapon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.weapon', verbose_name='Табельное оружие')),
            ],
        ),
    ]
